/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as ApiPublicWaWebhookRouteImport } from './routes/api/public/wa-webhook'
import { Route as ApiPublicBillingWebhookRouteImport } from './routes/api/public/billing-webhook'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/app/users'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppPreferencesRouteImport } from './routes/_authenticated/app/preferences'
import { Route as AuthenticatedAppMasterRouteImport } from './routes/_authenticated/app/master'
import { Route as AuthenticatedAppMarketplaceRouteImport } from './routes/_authenticated/app/marketplace'
import { Route as AuthenticatedAppAssistantRouteImport } from './routes/_authenticated/app/assistant'
import { Route as AuthenticatedAppInboxIndexRouteImport } from './routes/_authenticated/app/inbox/index'
import { Route as AuthenticatedAppCrmIndexRouteImport } from './routes/_authenticated/app/crm/index'
import { Route as AuthenticatedAppSettingsBillingRouteImport } from './routes/_authenticated/app/settings/billing'
import { Route as AuthenticatedAppSettingsAiRouteImport } from './routes/_authenticated/app/settings/ai'
import { Route as AuthenticatedAppInboxWhatsappRouteImport } from './routes/_authenticated/app/inbox/whatsapp'
import { Route as AuthenticatedAppInboxQueuesRouteImport } from './routes/_authenticated/app/inbox/queues'
import { Route as AuthenticatedAppCrmTagsRouteImport } from './routes/_authenticated/app/crm/tags'
import { Route as AuthenticatedAppCrmSettingsRouteImport } from './routes/_authenticated/app/crm/settings'
import { Route as AuthenticatedAppCrmLeadsRouteImport } from './routes/_authenticated/app/crm/leads'
import { Route as AuthenticatedAppCrmCustomersRouteImport } from './routes/_authenticated/app/crm/customers'
import { Route as AuthenticatedAppCrmContactsRouteImport } from './routes/_authenticated/app/crm/contacts'
import { Route as AuthenticatedAppCrmCompaniesRouteImport } from './routes/_authenticated/app/crm/companies'
import { Route as AuthenticatedAppCrmAutomationsRouteImport } from './routes/_authenticated/app/crm/automations'
import { Route as AuthenticatedAppCrmPipelinesIndexRouteImport } from './routes/_authenticated/app/crm/pipelines/index'
import { Route as AuthenticatedAppCrmPipelinesPipelineIdRouteImport } from './routes/_authenticated/app/crm/pipelines/$pipelineId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const ApiPublicWaWebhookRoute = ApiPublicWaWebhookRouteImport.update({
  id: '/api/public/wa-webhook',
  path: '/api/public/wa-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingWebhookRoute = ApiPublicBillingWebhookRouteImport.update({
  id: '/api/public/billing-webhook',
  path: '/api/public/billing-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPreferencesRoute =
  AuthenticatedAppPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMasterRoute = AuthenticatedAppMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppMarketplaceRoute =
  AuthenticatedAppMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAssistantRoute =
  AuthenticatedAppAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppInboxIndexRoute =
  AuthenticatedAppInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmIndexRoute =
  AuthenticatedAppCrmIndexRouteImport.update({
    id: '/crm/',
    path: '/crm/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsBillingRoute =
  AuthenticatedAppSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsAiRoute =
  AuthenticatedAppSettingsAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppInboxWhatsappRoute =
  AuthenticatedAppInboxWhatsappRouteImport.update({
    id: '/inbox/whatsapp',
    path: '/inbox/whatsapp',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppInboxQueuesRoute =
  AuthenticatedAppInboxQueuesRouteImport.update({
    id: '/inbox/queues',
    path: '/inbox/queues',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmTagsRoute = AuthenticatedAppCrmTagsRouteImport.update({
  id: '/crm/tags',
  path: '/crm/tags',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCrmSettingsRoute =
  AuthenticatedAppCrmSettingsRouteImport.update({
    id: '/crm/settings',
    path: '/crm/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmLeadsRoute =
  AuthenticatedAppCrmLeadsRouteImport.update({
    id: '/crm/leads',
    path: '/crm/leads',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmCustomersRoute =
  AuthenticatedAppCrmCustomersRouteImport.update({
    id: '/crm/customers',
    path: '/crm/customers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmContactsRoute =
  AuthenticatedAppCrmContactsRouteImport.update({
    id: '/crm/contacts',
    path: '/crm/contacts',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmCompaniesRoute =
  AuthenticatedAppCrmCompaniesRouteImport.update({
    id: '/crm/companies',
    path: '/crm/companies',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmAutomationsRoute =
  AuthenticatedAppCrmAutomationsRouteImport.update({
    id: '/crm/automations',
    path: '/crm/automations',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmPipelinesIndexRoute =
  AuthenticatedAppCrmPipelinesIndexRouteImport.update({
    id: '/crm/pipelines/',
    path: '/crm/pipelines/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmPipelinesPipelineIdRoute =
  AuthenticatedAppCrmPipelinesPipelineIdRouteImport.update({
    id: '/crm/pipelines/$pipelineId',
    path: '/crm/pipelines/$pipelineId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/master': typeof AuthenticatedAppMasterRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/api/public/billing-webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/wa-webhook': typeof ApiPublicWaWebhookRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/crm/automations': typeof AuthenticatedAppCrmAutomationsRoute
  '/app/crm/companies': typeof AuthenticatedAppCrmCompaniesRoute
  '/app/crm/contacts': typeof AuthenticatedAppCrmContactsRoute
  '/app/crm/customers': typeof AuthenticatedAppCrmCustomersRoute
  '/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/app/crm/settings': typeof AuthenticatedAppCrmSettingsRoute
  '/app/crm/tags': typeof AuthenticatedAppCrmTagsRoute
  '/app/inbox/queues': typeof AuthenticatedAppInboxQueuesRoute
  '/app/inbox/whatsapp': typeof AuthenticatedAppInboxWhatsappRoute
  '/app/settings/ai': typeof AuthenticatedAppSettingsAiRoute
  '/app/settings/billing': typeof AuthenticatedAppSettingsBillingRoute
  '/app/crm/': typeof AuthenticatedAppCrmIndexRoute
  '/app/inbox/': typeof AuthenticatedAppInboxIndexRoute
  '/app/crm/pipelines/$pipelineId': typeof AuthenticatedAppCrmPipelinesPipelineIdRoute
  '/app/crm/pipelines/': typeof AuthenticatedAppCrmPipelinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/master': typeof AuthenticatedAppMasterRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/api/public/billing-webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/wa-webhook': typeof ApiPublicWaWebhookRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/crm/automations': typeof AuthenticatedAppCrmAutomationsRoute
  '/app/crm/companies': typeof AuthenticatedAppCrmCompaniesRoute
  '/app/crm/contacts': typeof AuthenticatedAppCrmContactsRoute
  '/app/crm/customers': typeof AuthenticatedAppCrmCustomersRoute
  '/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/app/crm/settings': typeof AuthenticatedAppCrmSettingsRoute
  '/app/crm/tags': typeof AuthenticatedAppCrmTagsRoute
  '/app/inbox/queues': typeof AuthenticatedAppInboxQueuesRoute
  '/app/inbox/whatsapp': typeof AuthenticatedAppInboxWhatsappRoute
  '/app/settings/ai': typeof AuthenticatedAppSettingsAiRoute
  '/app/settings/billing': typeof AuthenticatedAppSettingsBillingRoute
  '/app/crm': typeof AuthenticatedAppCrmIndexRoute
  '/app/inbox': typeof AuthenticatedAppInboxIndexRoute
  '/app/crm/pipelines/$pipelineId': typeof AuthenticatedAppCrmPipelinesPipelineIdRoute
  '/app/crm/pipelines': typeof AuthenticatedAppCrmPipelinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/_authenticated/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/_authenticated/app/master': typeof AuthenticatedAppMasterRoute
  '/_authenticated/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/api/public/billing-webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/wa-webhook': typeof ApiPublicWaWebhookRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/crm/automations': typeof AuthenticatedAppCrmAutomationsRoute
  '/_authenticated/app/crm/companies': typeof AuthenticatedAppCrmCompaniesRoute
  '/_authenticated/app/crm/contacts': typeof AuthenticatedAppCrmContactsRoute
  '/_authenticated/app/crm/customers': typeof AuthenticatedAppCrmCustomersRoute
  '/_authenticated/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/_authenticated/app/crm/settings': typeof AuthenticatedAppCrmSettingsRoute
  '/_authenticated/app/crm/tags': typeof AuthenticatedAppCrmTagsRoute
  '/_authenticated/app/inbox/queues': typeof AuthenticatedAppInboxQueuesRoute
  '/_authenticated/app/inbox/whatsapp': typeof AuthenticatedAppInboxWhatsappRoute
  '/_authenticated/app/settings/ai': typeof AuthenticatedAppSettingsAiRoute
  '/_authenticated/app/settings/billing': typeof AuthenticatedAppSettingsBillingRoute
  '/_authenticated/app/crm/': typeof AuthenticatedAppCrmIndexRoute
  '/_authenticated/app/inbox/': typeof AuthenticatedAppInboxIndexRoute
  '/_authenticated/app/crm/pipelines/$pipelineId': typeof AuthenticatedAppCrmPipelinesPipelineIdRoute
  '/_authenticated/app/crm/pipelines/': typeof AuthenticatedAppCrmPipelinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/onboarding'
    | '/api/chat'
    | '/app/assistant'
    | '/app/marketplace'
    | '/app/master'
    | '/app/preferences'
    | '/app/settings'
    | '/app/users'
    | '/api/public/billing-webhook'
    | '/api/public/wa-webhook'
    | '/app/'
    | '/app/crm/automations'
    | '/app/crm/companies'
    | '/app/crm/contacts'
    | '/app/crm/customers'
    | '/app/crm/leads'
    | '/app/crm/settings'
    | '/app/crm/tags'
    | '/app/inbox/queues'
    | '/app/inbox/whatsapp'
    | '/app/settings/ai'
    | '/app/settings/billing'
    | '/app/crm/'
    | '/app/inbox/'
    | '/app/crm/pipelines/$pipelineId'
    | '/app/crm/pipelines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/onboarding'
    | '/api/chat'
    | '/app/assistant'
    | '/app/marketplace'
    | '/app/master'
    | '/app/preferences'
    | '/app/settings'
    | '/app/users'
    | '/api/public/billing-webhook'
    | '/api/public/wa-webhook'
    | '/app'
    | '/app/crm/automations'
    | '/app/crm/companies'
    | '/app/crm/contacts'
    | '/app/crm/customers'
    | '/app/crm/leads'
    | '/app/crm/settings'
    | '/app/crm/tags'
    | '/app/inbox/queues'
    | '/app/inbox/whatsapp'
    | '/app/settings/ai'
    | '/app/settings/billing'
    | '/app/crm'
    | '/app/inbox'
    | '/app/crm/pipelines/$pipelineId'
    | '/app/crm/pipelines'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/api/chat'
    | '/_authenticated/app/assistant'
    | '/_authenticated/app/marketplace'
    | '/_authenticated/app/master'
    | '/_authenticated/app/preferences'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/users'
    | '/api/public/billing-webhook'
    | '/api/public/wa-webhook'
    | '/_authenticated/app/'
    | '/_authenticated/app/crm/automations'
    | '/_authenticated/app/crm/companies'
    | '/_authenticated/app/crm/contacts'
    | '/_authenticated/app/crm/customers'
    | '/_authenticated/app/crm/leads'
    | '/_authenticated/app/crm/settings'
    | '/_authenticated/app/crm/tags'
    | '/_authenticated/app/inbox/queues'
    | '/_authenticated/app/inbox/whatsapp'
    | '/_authenticated/app/settings/ai'
    | '/_authenticated/app/settings/billing'
    | '/_authenticated/app/crm/'
    | '/_authenticated/app/inbox/'
    | '/_authenticated/app/crm/pipelines/$pipelineId'
    | '/_authenticated/app/crm/pipelines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicBillingWebhookRoute: typeof ApiPublicBillingWebhookRoute
  ApiPublicWaWebhookRoute: typeof ApiPublicWaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/public/wa-webhook': {
      id: '/api/public/wa-webhook'
      path: '/api/public/wa-webhook'
      fullPath: '/api/public/wa-webhook'
      preLoaderRoute: typeof ApiPublicWaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing-webhook': {
      id: '/api/public/billing-webhook'
      path: '/api/public/billing-webhook'
      fullPath: '/api/public/billing-webhook'
      preLoaderRoute: typeof ApiPublicBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/preferences': {
      id: '/_authenticated/app/preferences'
      path: '/preferences'
      fullPath: '/app/preferences'
      preLoaderRoute: typeof AuthenticatedAppPreferencesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/master': {
      id: '/_authenticated/app/master'
      path: '/master'
      fullPath: '/app/master'
      preLoaderRoute: typeof AuthenticatedAppMasterRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/marketplace': {
      id: '/_authenticated/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/assistant': {
      id: '/_authenticated/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AuthenticatedAppAssistantRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/inbox/': {
      id: '/_authenticated/app/inbox/'
      path: '/inbox'
      fullPath: '/app/inbox/'
      preLoaderRoute: typeof AuthenticatedAppInboxIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/': {
      id: '/_authenticated/app/crm/'
      path: '/crm'
      fullPath: '/app/crm/'
      preLoaderRoute: typeof AuthenticatedAppCrmIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings/billing': {
      id: '/_authenticated/app/settings/billing'
      path: '/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AuthenticatedAppSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/ai': {
      id: '/_authenticated/app/settings/ai'
      path: '/ai'
      fullPath: '/app/settings/ai'
      preLoaderRoute: typeof AuthenticatedAppSettingsAiRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/inbox/whatsapp': {
      id: '/_authenticated/app/inbox/whatsapp'
      path: '/inbox/whatsapp'
      fullPath: '/app/inbox/whatsapp'
      preLoaderRoute: typeof AuthenticatedAppInboxWhatsappRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/inbox/queues': {
      id: '/_authenticated/app/inbox/queues'
      path: '/inbox/queues'
      fullPath: '/app/inbox/queues'
      preLoaderRoute: typeof AuthenticatedAppInboxQueuesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/tags': {
      id: '/_authenticated/app/crm/tags'
      path: '/crm/tags'
      fullPath: '/app/crm/tags'
      preLoaderRoute: typeof AuthenticatedAppCrmTagsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/settings': {
      id: '/_authenticated/app/crm/settings'
      path: '/crm/settings'
      fullPath: '/app/crm/settings'
      preLoaderRoute: typeof AuthenticatedAppCrmSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/leads': {
      id: '/_authenticated/app/crm/leads'
      path: '/crm/leads'
      fullPath: '/app/crm/leads'
      preLoaderRoute: typeof AuthenticatedAppCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/customers': {
      id: '/_authenticated/app/crm/customers'
      path: '/crm/customers'
      fullPath: '/app/crm/customers'
      preLoaderRoute: typeof AuthenticatedAppCrmCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/contacts': {
      id: '/_authenticated/app/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/app/crm/contacts'
      preLoaderRoute: typeof AuthenticatedAppCrmContactsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/companies': {
      id: '/_authenticated/app/crm/companies'
      path: '/crm/companies'
      fullPath: '/app/crm/companies'
      preLoaderRoute: typeof AuthenticatedAppCrmCompaniesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/automations': {
      id: '/_authenticated/app/crm/automations'
      path: '/crm/automations'
      fullPath: '/app/crm/automations'
      preLoaderRoute: typeof AuthenticatedAppCrmAutomationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/pipelines/': {
      id: '/_authenticated/app/crm/pipelines/'
      path: '/crm/pipelines'
      fullPath: '/app/crm/pipelines/'
      preLoaderRoute: typeof AuthenticatedAppCrmPipelinesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/pipelines/$pipelineId': {
      id: '/_authenticated/app/crm/pipelines/$pipelineId'
      path: '/crm/pipelines/$pipelineId'
      fullPath: '/app/crm/pipelines/$pipelineId'
      preLoaderRoute: typeof AuthenticatedAppCrmPipelinesPipelineIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsAiRoute: typeof AuthenticatedAppSettingsAiRoute
  AuthenticatedAppSettingsBillingRoute: typeof AuthenticatedAppSettingsBillingRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsAiRoute: AuthenticatedAppSettingsAiRoute,
    AuthenticatedAppSettingsBillingRoute: AuthenticatedAppSettingsBillingRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAssistantRoute: typeof AuthenticatedAppAssistantRoute
  AuthenticatedAppMarketplaceRoute: typeof AuthenticatedAppMarketplaceRoute
  AuthenticatedAppMasterRoute: typeof AuthenticatedAppMasterRoute
  AuthenticatedAppPreferencesRoute: typeof AuthenticatedAppPreferencesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCrmAutomationsRoute: typeof AuthenticatedAppCrmAutomationsRoute
  AuthenticatedAppCrmCompaniesRoute: typeof AuthenticatedAppCrmCompaniesRoute
  AuthenticatedAppCrmContactsRoute: typeof AuthenticatedAppCrmContactsRoute
  AuthenticatedAppCrmCustomersRoute: typeof AuthenticatedAppCrmCustomersRoute
  AuthenticatedAppCrmLeadsRoute: typeof AuthenticatedAppCrmLeadsRoute
  AuthenticatedAppCrmSettingsRoute: typeof AuthenticatedAppCrmSettingsRoute
  AuthenticatedAppCrmTagsRoute: typeof AuthenticatedAppCrmTagsRoute
  AuthenticatedAppInboxQueuesRoute: typeof AuthenticatedAppInboxQueuesRoute
  AuthenticatedAppInboxWhatsappRoute: typeof AuthenticatedAppInboxWhatsappRoute
  AuthenticatedAppCrmIndexRoute: typeof AuthenticatedAppCrmIndexRoute
  AuthenticatedAppInboxIndexRoute: typeof AuthenticatedAppInboxIndexRoute
  AuthenticatedAppCrmPipelinesPipelineIdRoute: typeof AuthenticatedAppCrmPipelinesPipelineIdRoute
  AuthenticatedAppCrmPipelinesIndexRoute: typeof AuthenticatedAppCrmPipelinesIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAssistantRoute: AuthenticatedAppAssistantRoute,
  AuthenticatedAppMarketplaceRoute: AuthenticatedAppMarketplaceRoute,
  AuthenticatedAppMasterRoute: AuthenticatedAppMasterRoute,
  AuthenticatedAppPreferencesRoute: AuthenticatedAppPreferencesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCrmAutomationsRoute: AuthenticatedAppCrmAutomationsRoute,
  AuthenticatedAppCrmCompaniesRoute: AuthenticatedAppCrmCompaniesRoute,
  AuthenticatedAppCrmContactsRoute: AuthenticatedAppCrmContactsRoute,
  AuthenticatedAppCrmCustomersRoute: AuthenticatedAppCrmCustomersRoute,
  AuthenticatedAppCrmLeadsRoute: AuthenticatedAppCrmLeadsRoute,
  AuthenticatedAppCrmSettingsRoute: AuthenticatedAppCrmSettingsRoute,
  AuthenticatedAppCrmTagsRoute: AuthenticatedAppCrmTagsRoute,
  AuthenticatedAppInboxQueuesRoute: AuthenticatedAppInboxQueuesRoute,
  AuthenticatedAppInboxWhatsappRoute: AuthenticatedAppInboxWhatsappRoute,
  AuthenticatedAppCrmIndexRoute: AuthenticatedAppCrmIndexRoute,
  AuthenticatedAppInboxIndexRoute: AuthenticatedAppInboxIndexRoute,
  AuthenticatedAppCrmPipelinesPipelineIdRoute:
    AuthenticatedAppCrmPipelinesPipelineIdRoute,
  AuthenticatedAppCrmPipelinesIndexRoute:
    AuthenticatedAppCrmPipelinesIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicBillingWebhookRoute: ApiPublicBillingWebhookRoute,
  ApiPublicWaWebhookRoute: ApiPublicWaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
