/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/app/users'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppPreferencesRouteImport } from './routes/_authenticated/app/preferences'
import { Route as AuthenticatedAppMasterRouteImport } from './routes/_authenticated/app/master'
import { Route as AuthenticatedAppCrmIndexRouteImport } from './routes/_authenticated/app/crm/index'
import { Route as AuthenticatedAppCrmTagsRouteImport } from './routes/_authenticated/app/crm/tags'
import { Route as AuthenticatedAppCrmSettingsRouteImport } from './routes/_authenticated/app/crm/settings'
import { Route as AuthenticatedAppCrmLeadsRouteImport } from './routes/_authenticated/app/crm/leads'
import { Route as AuthenticatedAppCrmCustomersRouteImport } from './routes/_authenticated/app/crm/customers'
import { Route as AuthenticatedAppCrmContactsRouteImport } from './routes/_authenticated/app/crm/contacts'
import { Route as AuthenticatedAppCrmCompaniesRouteImport } from './routes/_authenticated/app/crm/companies'
import { Route as AuthenticatedAppCrmAutomationsRouteImport } from './routes/_authenticated/app/crm/automations'
import { Route as AuthenticatedAppCrmPipelinesIndexRouteImport } from './routes/_authenticated/app/crm/pipelines/index'
import { Route as AuthenticatedAppCrmPipelinesPipelineIdRouteImport } from './routes/_authenticated/app/crm/pipelines/$pipelineId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPreferencesRoute =
  AuthenticatedAppPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMasterRoute = AuthenticatedAppMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCrmIndexRoute =
  AuthenticatedAppCrmIndexRouteImport.update({
    id: '/crm/',
    path: '/crm/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmTagsRoute = AuthenticatedAppCrmTagsRouteImport.update({
  id: '/crm/tags',
  path: '/crm/tags',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCrmSettingsRoute =
  AuthenticatedAppCrmSettingsRouteImport.update({
    id: '/crm/settings',
    path: '/crm/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmLeadsRoute =
  AuthenticatedAppCrmLeadsRouteImport.update({
    id: '/crm/leads',
    path: '/crm/leads',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmCustomersRoute =
  AuthenticatedAppCrmCustomersRouteImport.update({
    id: '/crm/customers',
    path: '/crm/customers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmContactsRoute =
  AuthenticatedAppCrmContactsRouteImport.update({
    id: '/crm/contacts',
    path: '/crm/contacts',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmCompaniesRoute =
  AuthenticatedAppCrmCompaniesRouteImport.update({
    id: '/crm/companies',
    path: '/crm/companies',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmAutomationsRoute =
  AuthenticatedAppCrmAutomationsRouteImport.update({
    id: '/crm/automations',
    path: '/crm/automations',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmPipelinesIndexRoute =
  AuthenticatedAppCrmPipelinesIndexRouteImport.update({
    id: '/crm/pipelines/',
    path: '/crm/pipelines/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCrmPipelinesPipelineIdRoute =
  AuthenticatedAppCrmPipelinesPipelineIdRouteImport.update({
    id: '/crm/pipelines/$pipelineId',
    path: '/crm/pipelines/$pipelineId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/master': typeof AuthenticatedAppMasterRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/crm/automations': typeof AuthenticatedAppCrmAutomationsRoute
  '/app/crm/companies': typeof AuthenticatedAppCrmCompaniesRoute
  '/app/crm/contacts': typeof AuthenticatedAppCrmContactsRoute
  '/app/crm/customers': typeof AuthenticatedAppCrmCustomersRoute
  '/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/app/crm/settings': typeof AuthenticatedAppCrmSettingsRoute
  '/app/crm/tags': typeof AuthenticatedAppCrmTagsRoute
  '/app/crm/': typeof AuthenticatedAppCrmIndexRoute
  '/app/crm/pipelines/$pipelineId': typeof AuthenticatedAppCrmPipelinesPipelineIdRoute
  '/app/crm/pipelines/': typeof AuthenticatedAppCrmPipelinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/master': typeof AuthenticatedAppMasterRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/crm/automations': typeof AuthenticatedAppCrmAutomationsRoute
  '/app/crm/companies': typeof AuthenticatedAppCrmCompaniesRoute
  '/app/crm/contacts': typeof AuthenticatedAppCrmContactsRoute
  '/app/crm/customers': typeof AuthenticatedAppCrmCustomersRoute
  '/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/app/crm/settings': typeof AuthenticatedAppCrmSettingsRoute
  '/app/crm/tags': typeof AuthenticatedAppCrmTagsRoute
  '/app/crm': typeof AuthenticatedAppCrmIndexRoute
  '/app/crm/pipelines/$pipelineId': typeof AuthenticatedAppCrmPipelinesPipelineIdRoute
  '/app/crm/pipelines': typeof AuthenticatedAppCrmPipelinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/app/master': typeof AuthenticatedAppMasterRoute
  '/_authenticated/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/crm/automations': typeof AuthenticatedAppCrmAutomationsRoute
  '/_authenticated/app/crm/companies': typeof AuthenticatedAppCrmCompaniesRoute
  '/_authenticated/app/crm/contacts': typeof AuthenticatedAppCrmContactsRoute
  '/_authenticated/app/crm/customers': typeof AuthenticatedAppCrmCustomersRoute
  '/_authenticated/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/_authenticated/app/crm/settings': typeof AuthenticatedAppCrmSettingsRoute
  '/_authenticated/app/crm/tags': typeof AuthenticatedAppCrmTagsRoute
  '/_authenticated/app/crm/': typeof AuthenticatedAppCrmIndexRoute
  '/_authenticated/app/crm/pipelines/$pipelineId': typeof AuthenticatedAppCrmPipelinesPipelineIdRoute
  '/_authenticated/app/crm/pipelines/': typeof AuthenticatedAppCrmPipelinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/onboarding'
    | '/app/master'
    | '/app/preferences'
    | '/app/settings'
    | '/app/users'
    | '/app/'
    | '/app/crm/automations'
    | '/app/crm/companies'
    | '/app/crm/contacts'
    | '/app/crm/customers'
    | '/app/crm/leads'
    | '/app/crm/settings'
    | '/app/crm/tags'
    | '/app/crm/'
    | '/app/crm/pipelines/$pipelineId'
    | '/app/crm/pipelines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/onboarding'
    | '/app/master'
    | '/app/preferences'
    | '/app/settings'
    | '/app/users'
    | '/app'
    | '/app/crm/automations'
    | '/app/crm/companies'
    | '/app/crm/contacts'
    | '/app/crm/customers'
    | '/app/crm/leads'
    | '/app/crm/settings'
    | '/app/crm/tags'
    | '/app/crm'
    | '/app/crm/pipelines/$pipelineId'
    | '/app/crm/pipelines'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/app/master'
    | '/_authenticated/app/preferences'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/users'
    | '/_authenticated/app/'
    | '/_authenticated/app/crm/automations'
    | '/_authenticated/app/crm/companies'
    | '/_authenticated/app/crm/contacts'
    | '/_authenticated/app/crm/customers'
    | '/_authenticated/app/crm/leads'
    | '/_authenticated/app/crm/settings'
    | '/_authenticated/app/crm/tags'
    | '/_authenticated/app/crm/'
    | '/_authenticated/app/crm/pipelines/$pipelineId'
    | '/_authenticated/app/crm/pipelines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/preferences': {
      id: '/_authenticated/app/preferences'
      path: '/preferences'
      fullPath: '/app/preferences'
      preLoaderRoute: typeof AuthenticatedAppPreferencesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/master': {
      id: '/_authenticated/app/master'
      path: '/master'
      fullPath: '/app/master'
      preLoaderRoute: typeof AuthenticatedAppMasterRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/': {
      id: '/_authenticated/app/crm/'
      path: '/crm'
      fullPath: '/app/crm/'
      preLoaderRoute: typeof AuthenticatedAppCrmIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/tags': {
      id: '/_authenticated/app/crm/tags'
      path: '/crm/tags'
      fullPath: '/app/crm/tags'
      preLoaderRoute: typeof AuthenticatedAppCrmTagsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/settings': {
      id: '/_authenticated/app/crm/settings'
      path: '/crm/settings'
      fullPath: '/app/crm/settings'
      preLoaderRoute: typeof AuthenticatedAppCrmSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/leads': {
      id: '/_authenticated/app/crm/leads'
      path: '/crm/leads'
      fullPath: '/app/crm/leads'
      preLoaderRoute: typeof AuthenticatedAppCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/customers': {
      id: '/_authenticated/app/crm/customers'
      path: '/crm/customers'
      fullPath: '/app/crm/customers'
      preLoaderRoute: typeof AuthenticatedAppCrmCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/contacts': {
      id: '/_authenticated/app/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/app/crm/contacts'
      preLoaderRoute: typeof AuthenticatedAppCrmContactsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/companies': {
      id: '/_authenticated/app/crm/companies'
      path: '/crm/companies'
      fullPath: '/app/crm/companies'
      preLoaderRoute: typeof AuthenticatedAppCrmCompaniesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/automations': {
      id: '/_authenticated/app/crm/automations'
      path: '/crm/automations'
      fullPath: '/app/crm/automations'
      preLoaderRoute: typeof AuthenticatedAppCrmAutomationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/pipelines/': {
      id: '/_authenticated/app/crm/pipelines/'
      path: '/crm/pipelines'
      fullPath: '/app/crm/pipelines/'
      preLoaderRoute: typeof AuthenticatedAppCrmPipelinesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/crm/pipelines/$pipelineId': {
      id: '/_authenticated/app/crm/pipelines/$pipelineId'
      path: '/crm/pipelines/$pipelineId'
      fullPath: '/app/crm/pipelines/$pipelineId'
      preLoaderRoute: typeof AuthenticatedAppCrmPipelinesPipelineIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppMasterRoute: typeof AuthenticatedAppMasterRoute
  AuthenticatedAppPreferencesRoute: typeof AuthenticatedAppPreferencesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCrmAutomationsRoute: typeof AuthenticatedAppCrmAutomationsRoute
  AuthenticatedAppCrmCompaniesRoute: typeof AuthenticatedAppCrmCompaniesRoute
  AuthenticatedAppCrmContactsRoute: typeof AuthenticatedAppCrmContactsRoute
  AuthenticatedAppCrmCustomersRoute: typeof AuthenticatedAppCrmCustomersRoute
  AuthenticatedAppCrmLeadsRoute: typeof AuthenticatedAppCrmLeadsRoute
  AuthenticatedAppCrmSettingsRoute: typeof AuthenticatedAppCrmSettingsRoute
  AuthenticatedAppCrmTagsRoute: typeof AuthenticatedAppCrmTagsRoute
  AuthenticatedAppCrmIndexRoute: typeof AuthenticatedAppCrmIndexRoute
  AuthenticatedAppCrmPipelinesPipelineIdRoute: typeof AuthenticatedAppCrmPipelinesPipelineIdRoute
  AuthenticatedAppCrmPipelinesIndexRoute: typeof AuthenticatedAppCrmPipelinesIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppMasterRoute: AuthenticatedAppMasterRoute,
  AuthenticatedAppPreferencesRoute: AuthenticatedAppPreferencesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCrmAutomationsRoute: AuthenticatedAppCrmAutomationsRoute,
  AuthenticatedAppCrmCompaniesRoute: AuthenticatedAppCrmCompaniesRoute,
  AuthenticatedAppCrmContactsRoute: AuthenticatedAppCrmContactsRoute,
  AuthenticatedAppCrmCustomersRoute: AuthenticatedAppCrmCustomersRoute,
  AuthenticatedAppCrmLeadsRoute: AuthenticatedAppCrmLeadsRoute,
  AuthenticatedAppCrmSettingsRoute: AuthenticatedAppCrmSettingsRoute,
  AuthenticatedAppCrmTagsRoute: AuthenticatedAppCrmTagsRoute,
  AuthenticatedAppCrmIndexRoute: AuthenticatedAppCrmIndexRoute,
  AuthenticatedAppCrmPipelinesPipelineIdRoute:
    AuthenticatedAppCrmPipelinesPipelineIdRoute,
  AuthenticatedAppCrmPipelinesIndexRoute:
    AuthenticatedAppCrmPipelinesIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
